services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: appdiet
      POSTGRES_USER: appdiet
      POSTGRES_PASSWORD: appdiet
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
